version: 2
updates:
  - package-ecosystem: gradle
    directory: "/android-emulator-plugin"
    schedule:
      interval: monthly
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
